backend:
  name: github
  repo: brookeangel/oakland-history-map
media_folder: static/assets
public_folder: /assets
collections:
  - name: sites
    label: Site
    folder: sites
    create: true
    fields:
      - { name: name, label: Name }
      - { name: path, label: Path }
      - { name: entryDate, label: Entry Date, widget: datetime }
      - { name: startDate, label: Start Date, widget: date, required: false }
      - { name: endDate, label: End Date, widget: date, required: false }
      - { name: location, label: Location, widget: address }
      - { name: image, label: Image, widget: image, required: false }
      - { name: body, label: Body, widget: markdown }
